### ISSUE TITLE
Generating dynamic routes with apollo in nuxt.config

### ISSUE THREAD

**Issue by dacarva** [GraphCMS/graphcms-examples#111]
Hi!
I have been struggling with the generation of dynamic routes in nuxt.config.js 

The example in axios is the following:
`import axios from 'axios'
let dynamicRoutes = () => {
 return axios.get('https://your-api-here/products').then(res => {
   return res.data.map(product => `/product/${product.id}`)
 })
}`

Can you please help me with this?

Thanks

**Comment by notrab** [comment]
Hi @dacarva 

Apologies we missed this. Did you manage to get this sorted in the end? I'd recommend heading to Spectrum or Vue/Nuxt channels to get more dedicated support on the individual frameworks.

I can try to help as much as possible but the pros on those forums would be better equipped 😉 

Feel free to re-open if this is still an issue.
