### ISSUE TITLE
Surge deployment

### ISSUE THREAD

**Issue by dancomanlive** [GraphCMS/graphcms-examples#3]
The example react-static-gql-request-blog works on local host. When deploying with surge(https://surge.sh) 

```
npm run build

> react-static-example-basic@1.0.1 build /Users/dancoman/Workspace/graphcms-examples/react-static-gql-request-blog
> react-static build


=> Copying public directory...
=> [✓] Public directory copied: 3.857ms
=> Building Routes...
=> [✓] Routes Built: 930.920ms
=> Bundling App...
=> [✓] App Bundled: 13819.881ms
=> Exporting Routes...

      => Warning: No 'siteRoot' defined in 'static.config.js'!
      => This is required for both absolute url's and a sitemap.xml to be exported.
```

A solution would be highly appreciated, even though this is not strictly related to this repo.

**Comment by sintaxi** [comment]
Sorry if Im missing something here. What does this have to do with surge?

**Comment by dancomanlive** [comment]
It's a surge-related question, in order to ask a question one needs to open an issue. Would be great to get an answer to this question if possible :)

**Comment by sintaxi** [comment]
As far as I can tell this script is failing before surge gets called. I would look to see what your `scripts` > `build` command calls in your `package.json` file. My guess is react-static is looking for a `siteRoot` value which points to what the static directory is which its looking for in a `static.config.js` file. Thats just a guess though. Hope this helps.

**Comment by dancomanlive** [comment]
Thanks for the reply and willingness to help out. I fixed by running surge dist. Everything works as expected. Love GraphCMS <3

**Comment by sintaxi** [comment]
Beautiful. Please excuse my initial reply, I thought this was the surge issue tracker so I was confused by the stack trace provided. Glad it got resolved.
