### ISSUE TITLE
How to load Nuxt-Appollo-Blog on the Server Side?

### ISSUE THREAD

**Issue by faia20** [GraphCMS/graphcms-examples#4]
Hi,

Great job with the GraphCMS, it's really awesome!

I'm new using Apollo and GraphQL. I would like to run this blog example on the server side, so when I check the source code on the browser I can see the whole content. This is just for SEO reasons.

Many thanks

**Comment by hmeissner** [comment]
Hey @faia20, Nuxt provides server side rendering for your application by default. There are no additional steps required to make it work, everything is rendered on the server before being sent to you. 🙂 

Seeing as this is also not an issue with examples themselves, I'm closing this and would recommend that you dig into [Nuxt documentation](https://nuxtjs.org/guide) to learn more about how Nuxt handles your app.

And if you have any questions regarding the GraphCMS integration in the example, please come and join us on our [community Slack](https://slack.graphcms.com) and post your questions there 🙂
