### ISSUE TITLE
react-apollo-blog names

### ISSUE THREAD

**Issue by ACC-Nexus** [GraphCMS/graphcms-examples#5]
The names of some of the fields in the code are different than the instructions here: https://graphcms.com/docs/getting-started/setting_up_the_project/

"dateAndTime" should be "dateTime" and "avatar" should be "image".

The affected files are Home.js, About.js and Post.js

**Comment by hmeissner** [comment]
Hey @ACC-Nexus, thanks for pointing this out but it's actually the fault of screenshots in the guide. They will be corrected with the new version of our webapp 🙂

The examples are actually fine and changing those field names would currenlty result in errors while fetching data. For this reason I'm also closing https://github.com/GraphCMS/graphcms-examples/pull/6
