### ISSUE TITLE
Please provide GraphCMS example for Gridsome too

### ISSUE THREAD

**Issue by IamManchanda** [GraphCMS/graphcms-examples#94]
https://gridsome.org/

cc @tomtev of Gridsome

<img width="448" alt="Screenshot 2019-07-14 at 2 41 04 PM" src="https://user-images.githubusercontent.com/4970624/61181578-1dd60e80-a646-11e9-984a-cb5622224615.png">

**Comment by notrab** [comment]
Hi @IamManchanda 

Thanks for the request, and apologies for the delayed request!

It's on our backlog but feel free to PR this repo if you want to share anything Gridsome related.
